spring.application.name=ranking-service

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

travelmate.exchange.trip=travelmate.trip.x
travelmate.queue.trip-planned=travelmate.trip.planned.q
travelmate.routing.trip-planned=trip.planned

spring.rabbitmq.listener.simple.missing-queues-fatal=false
